### ISSUE TITLE
Introductory code reports error (due to player names encoding)

### ISSUE THREAD

**Issue by justa9** [bziarkowski/euRobasket#1]
Hello.

I tried to follow along the introductory code, but I encountered an error in ```on_off_splits```.

After running the function through debug, I noticed that the result of ```players %in% stint_players$Player``` is: "[1] FALSE  TRUE", while a visual inspection showed that both names exist. However, the encoding is not consistent, thus I think there might be a reason to force all string matches be done in UTF-8.

Hope I presented the issue in a comprehensible way.

Thank you.

**Comment by bziarkowski** [comment]
Changed encoding to UTF-8 in `on_off_splits`. Try now.

**Comment by justa9** [comment]
Thank you (for this, and the rest of the fixes). It now seems to work.
